import React, { useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { toast } from "react-toastify";

const RoadmapModal: React.FC<{
  open: boolean;
  onClose: () => void;
  plan: string;
  loading?: boolean;
  error?: string;
  onEditRoadmap?: () => void;
}> = ({ open, onClose, plan, loading = false, error, onEditRoadmap }) => {
  const [isDownloading, setIsDownloading] = useState(false);
  const [isSharing, setIsSharing] = useState(false);

  if (!open) return null;

  // Function to download PDF
  const handleDownloadPDF = async () => {
    setIsDownloading(true);
    try {
      // Create a downloadable text file with the roadmap content
      const element = document.createElement('a');
      const file = new Blob([plan], { type: 'text/plain' });
      element.href = URL.createObjectURL(file);
      element.download = 'startup-roadmap.txt';
      document.body.appendChild(element);
      element.click();
      document.body.removeChild(element);
      
      toast.success('Startup roadmap downloaded successfully!');
    } catch (error) {
      toast.error('Failed to download startup roadmap');
    } finally {
      setIsDownloading(false);
    }
  };

  // Function to share roadmap
  const handleShareRoadmap = async () => {
    setIsSharing(true);
    try {
      if (navigator.share) {
        await navigator.share({
          title: 'My Startup Roadmap',
          text: 'Check out my startup roadmap generated by Angel AI',
          url: window.location.href
        });
        toast.success('Startup roadmap shared successfully!');
      } else {
        // Fallback: copy to clipboard
        await navigator.clipboard.writeText(plan);
        toast.success('Startup roadmap copied to clipboard!');
      }
    } catch (error: any) {
      if (error.name !== 'AbortError') {
        // Fallback: copy to clipboard
        try {
          await navigator.clipboard.writeText(plan);
          toast.success('Startup roadmap copied to clipboard!');
        } catch (clipboardError) {
          toast.error('Failed to share startup roadmap');
        }
      }
    } finally {
      setIsSharing(false);
    }
  };

  // Function to edit roadmap
  const handleEditRoadmap = () => {
    if (onEditRoadmap) {
      onEditRoadmap();
      toast.info('Edit mode activated. You can now modify your roadmap responses.');
    } else {
      toast.info('Edit functionality will be available soon.');
    }
  };

  const formatTableCell = (cell: string): string =>
    cell
      .replace(/\*\*(.*?)\*\*/g, '<strong class="font-semibold text-gray-900">$1</strong>')
      .replace(/`([^`]+)`/g, '<code class="px-1.5 py-0.5 rounded bg-slate-100 text-slate-700 text-xs">$1</code>')
      .replace(/<br>/g, '<br/>')
      .replace(/\n/g, '<br/>');

  const sanitizeTimeline = (value: string): string =>
    value
      .replace(/\*\*(.*?)\*\*/g, '$1')
      .replace(/<br\s*\/?>/gi, ' • ')
      .replace(/\n/g, ' ')
      .replace(/\s+/g, ' ')
      .trim();

  // Format non-table content (bold, italics, lists, etc.)
  const formatNonTableContent = (text: string): string => {
    const styled = text
      .replace(/\*\*(.*?)\*\*/g, '<strong class="font-bold text-gray-900">$1</strong>')
      .replace(/\*(.*?)\*/g, '<em class="italic text-gray-700">$1</em>')
      .replace(/^# (.*$)/gim, '<h1 class="text-4xl font-bold text-slate-900 mb-6 mt-12 border-b border-slate-200 pb-3">$1</h1>')
      .replace(/^## (.*$)/gim, '<h2 class="text-2xl font-semibold text-slate-800 mt-10 mb-4 border-l-4 border-blue-600 pl-4">$1</h2>')
      .replace(/^### (.*$)/gim, '<h3 class="text-xl font-medium text-slate-700 mt-6 mb-2">$1</h3>')
      .replace(/^---$/gim, '<hr class="my-10 border-slate-300"/>')
      .replace(/^• (.*$)/gim, '<li class="ml-4 leading-relaxed text-slate-700">$1</li>')
      .replace(/^- (.*$)/gim, '<li class="ml-4 leading-relaxed text-slate-700">$1</li>');

    return styled
      .replace(/\n\n/g, '<br/><br/>')
      .replace(/\n/g, '<br/>');
  };

  // Render a markdown table as an HTML table
  const renderTable = (lines: string[], key: string, contextTitle?: string): React.ReactNode => {
    if (lines.length < 2) return null;

    // Parse header
    const headerCells = lines[0]
      .split('|')
      .filter(cell => cell.trim())
      .map(cell => cell.trim());

    // Skip separator line (lines[1])
    // Parse data rows
    const dataRows = lines.slice(2)
      .filter(line => line.trim())
      .map(line => 
        line.split('|')
          .filter(cell => cell.trim())
          .map(cell => cell.trim())
      );

    // Check if this is a research source table
    const isResearchTable = headerCells.some(h => 
      h.toLowerCase().includes('research source') || 
      h.toLowerCase().includes('key findings') ||
      h.toLowerCase().includes('source type') ||
      h.toLowerCase().includes('specific sources')
    );

    // Check for step table format: Step Name | Step Description | Timeline | Research Source
    const isStepTable =
      headerCells.length >= 4 &&
      headerCells[0].toLowerCase().includes('step name') &&
      headerCells[1].toLowerCase().includes('step description') &&
      headerCells[2].toLowerCase().includes('timeline') &&
      headerCells[3].toLowerCase().includes('research source');

    // Check for roadmap table format: Task | Description | Dependencies | Angel's Role | Status
    const isRoadmapTable =
      headerCells.length >= 5 &&
      headerCells[0].toLowerCase().includes('task') &&
      headerCells[1].toLowerCase().includes('description') &&
      headerCells[2].toLowerCase().includes('dependencies') &&
      headerCells[3].toLowerCase().includes("angel") &&
      headerCells[4].toLowerCase().includes('status');

    // Render step table format
    if (isStepTable) {
      return (
        <div
          key={key}
          className="mb-10 rounded-3xl border border-indigo-200 shadow-[0_10px_30px_rgba(79,70,229,0.12)] overflow-hidden"
        >
          <div className="bg-gradient-to-r from-indigo-600 via-purple-600 to-sky-500 px-6 py-4">
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
              <h4 className="text-white text-lg font-semibold tracking-wide">
                {contextTitle || 'Roadmap Steps'}
              </h4>
              <span className="text-indigo-100 text-xs uppercase tracking-[0.2em]">
                Sequential Execution
              </span>
            </div>
          </div>
          <div className="overflow-x-auto bg-gradient-to-br from-white via-white to-indigo-50/20">
            <table className="min-w-full border-separate border-spacing-0">
              <thead>
                <tr className="bg-white">
                  <th className="w-16 px-4 py-3 text-left text-xs font-semibold text-indigo-600 uppercase tracking-wide border-b border-indigo-100">
                    #
                  </th>
                  <th className="px-4 py-3 text-left text-xs font-semibold text-indigo-600 uppercase tracking-wide border-b border-indigo-100">
                    Step & Guidance
                  </th>
                  <th className="w-44 px-4 py-3 text-left text-xs font-semibold text-indigo-600 uppercase tracking-wide border-b border-indigo-100">
                    Timeline
                  </th>
                  <th className="px-4 py-3 text-left text-xs font-semibold text-indigo-600 uppercase tracking-wide border-b border-indigo-100">
                    Research Sources
                  </th>
                </tr>
              </thead>
              <tbody>
                {dataRows.map((row, rowIdx) => {
                  const [stepTitle = '', stepDescription = '', timeline = '', source = ''] = row;
                  const stepNumber = rowIdx + 1;
                  return (
                    <tr
                      key={rowIdx}
                      className={`${
                        rowIdx % 2 === 0 ? 'bg-white' : 'bg-indigo-50/40'
                      } border-b border-indigo-100 last:border-none hover:bg-indigo-100/60 transition-colors`}
                    >
                      <td className="px-4 py-4 align-top">
                        <div className="inline-flex items-center justify-center rounded-full bg-gradient-to-br from-indigo-500 to-purple-600 text-white font-bold text-sm h-10 w-10 shadow-md">
                          {stepNumber}
                        </div>
                      </td>
                      <td className="px-4 py-4 align-top">
                        <div
                          className="text-base font-bold text-gray-900 mb-2"
                          dangerouslySetInnerHTML={{ __html: formatTableCell(stepTitle) }}
                        />
                        <div
                          className="text-sm leading-relaxed text-gray-700"
                          dangerouslySetInnerHTML={{ __html: formatTableCell(stepDescription) }}
                        />
                      </td>
                      <td className="px-4 py-4 align-top">
                        <span className="inline-flex items-center rounded-full bg-blue-100 text-blue-800 px-3 py-1.5 text-xs font-semibold border border-blue-200">
                          {sanitizeTimeline(timeline)}
                        </span>
                      </td>
                      <td className="px-4 py-4 align-top text-xs text-gray-700 leading-relaxed">
                        <div className="bg-gray-50 rounded-md p-2 border border-gray-200" dangerouslySetInnerHTML={{ __html: formatTableCell(source) }} />
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      );
    }

    // Render roadmap table format
    if (isRoadmapTable) {
      return (
        <div
          key={key}
          className="mb-10 rounded-3xl border border-indigo-200 shadow-[0_10px_30px_rgba(79,70,229,0.12)] overflow-hidden"
        >
          <div className="bg-gradient-to-r from-indigo-600 via-purple-600 to-sky-500 px-6 py-4">
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
              <h4 className="text-white text-lg font-semibold tracking-wide">
                {contextTitle || 'Roadmap Tasks'}
              </h4>
              <span className="text-indigo-100 text-xs uppercase tracking-[0.2em]">
                Sequential Execution
              </span>
            </div>
          </div>
          <div className="overflow-x-auto bg-gradient-to-br from-white via-white to-indigo-50/20">
            <table className="min-w-full border-separate border-spacing-0">
              <thead>
                <tr className="bg-white">
                  <th className="px-4 py-3 text-left text-xs font-semibold text-indigo-600 uppercase tracking-wide border-b border-indigo-100">
                    Task
                  </th>
                  <th className="px-4 py-3 text-left text-xs font-semibold text-indigo-600 uppercase tracking-wide border-b border-indigo-100">
                    Description
                  </th>
                  <th className="px-4 py-3 text-left text-xs font-semibold text-indigo-600 uppercase tracking-wide border-b border-indigo-100">
                    Dependencies
                  </th>
                  <th className="px-4 py-3 text-left text-xs font-semibold text-indigo-600 uppercase tracking-wide border-b border-indigo-100">
                    Angel's Role
                  </th>
                  <th className="w-20 px-4 py-3 text-center text-xs font-semibold text-indigo-600 uppercase tracking-wide border-b border-indigo-100">
                    Status
                  </th>
                </tr>
              </thead>
              <tbody>
                {dataRows.map((row, rowIdx) => {
                  const [task = '', description = '', dependencies = '', angelRole = '', status = '⬜'] = row;
                  const statusIcon = status.trim() === '✓' || status.trim() === '✅' ? '✓' : 
                                    status.trim() === '→' || status.toLowerCase().includes('soon') ? '→' : '⬜';
                  const statusColor = statusIcon === '✓' ? 'text-green-600' : 
                                     statusIcon === '→' ? 'text-orange-600' : 'text-gray-400';
                  
                  return (
                    <tr
                      key={rowIdx}
                      className={`${
                        rowIdx % 2 === 0 ? 'bg-white' : 'bg-indigo-50/40'
                      } border-b border-indigo-100 last:border-none hover:bg-indigo-100/60 transition-colors`}
                    >
                      <td className="px-4 py-4 align-top">
                        <div
                          className="text-base font-bold text-gray-900"
                          dangerouslySetInnerHTML={{ __html: formatTableCell(task) }}
                        />
                      </td>
                      <td className="px-4 py-4 align-top">
                        <div
                          className="text-sm leading-relaxed text-gray-700"
                          dangerouslySetInnerHTML={{ __html: formatTableCell(description) }}
                        />
                      </td>
                      <td className="px-4 py-4 align-top">
                        <div
                          className="text-sm text-gray-600 italic"
                          dangerouslySetInnerHTML={{ __html: formatTableCell(dependencies) }}
                        />
                      </td>
                      <td className="px-4 py-4 align-top">
                        <div
                          className="text-sm text-indigo-700"
                          dangerouslySetInnerHTML={{ __html: formatTableCell(angelRole) }}
                        />
                      </td>
                      <td className="px-4 py-4 align-top text-center">
                        <span className={`text-2xl ${statusColor}`}>
                          {statusIcon}
                        </span>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      );
    }

    // Default table rendering
    return (
      <div key={key} className="overflow-x-auto mb-6 shadow-md rounded-lg">
        <table className="min-w-full border-collapse bg-white rounded-lg overflow-hidden">
          <thead className={isResearchTable 
            ? "bg-gradient-to-r from-indigo-100 to-purple-100" 
            : "bg-gradient-to-r from-blue-50 to-indigo-50"
          }>
            <tr>
              {headerCells.map((header, idx) => (
                <th
                  key={idx}
                  className={`px-4 py-3 text-left text-xs sm:text-sm font-bold border-b-2 ${
                    isResearchTable ? 'text-indigo-900 border-indigo-300' : 'text-gray-900 border-indigo-200'
                  }`}
                >
                  {header}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {dataRows.map((row, rowIdx) => (
              <tr
                key={rowIdx}
                className={`${rowIdx % 2 === 0 ? 'bg-gray-50' : 'bg-white'} hover:bg-blue-50 transition-colors border-b border-gray-100`}
              >
                {row.map((cell, cellIdx) => {
                  const isResearchCell = headerCells[cellIdx]?.toLowerCase().includes('research source');
                  
                  return (
                    <td
                      key={cellIdx}
                      className={`px-4 py-3 text-xs sm:text-sm border-b border-gray-200 ${
                        isResearchCell ? 'bg-indigo-50/50' : ''
                      }`}
                      dangerouslySetInnerHTML={{
                        __html: formatTableCell(cell)
                          .replace(/\*Government\*/g, '<span class="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-blue-100 text-blue-800">🏛️ Government</span>')
                          .replace(/\*Academic\*/g, '<span class="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-purple-100 text-purple-800">🎓 Academic</span>')
                          .replace(/\*Industry\*/g, '<span class="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-orange-100 text-orange-800">📰 Industry</span>')
                      }}
                    />
                  );
                })}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    );
  };

  // Helper function to render markdown tables as HTML tables
  const renderMarkdownTable = (content: string): React.ReactNode => {
    const lines = content.split('\n');
    const elements: React.ReactNode[] = [];
    let inTable = false;
    let tableLines: string[] = [];
    let nonTableContent: string[] = [];
    let currentPhaseTitle = '';

    const flushNonTableContent = (key: string) => {
      if (nonTableContent.length > 0) {
        const formattedText = formatNonTableContent(nonTableContent.join('\n'));
        elements.push(
          <div key={key} className="mb-6" dangerouslySetInnerHTML={{ __html: formattedText }} />
        );
        nonTableContent = [];
      }
    };

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      const trimmedLine = line.trim();

      if (trimmedLine.startsWith('###')) {
        currentPhaseTitle = trimmedLine.replace(/^###\s*/, '').trim();
      } else if (/^\*\*Roadmap Steps -/i.test(trimmedLine)) {
        currentPhaseTitle = trimmedLine.replace(/\*\*/g, '').replace(/:$/, '').trim();
        continue;
      } else if (/^\*\*Service Providers/i.test(trimmedLine)) {
        currentPhaseTitle = trimmedLine.replace(/\*\*/g, '').replace(/:$/, '').trim();
      }
      
      // Check if line is a table row (starts with |)
      if (trimmedLine.startsWith('|')) {
        if (!inTable) {
          flushNonTableContent(`text-${i}`);
          inTable = true;
        }
        tableLines.push(line);
      } else {
        if (inTable) {
          // Render the accumulated table
          elements.push(renderTable(tableLines, `table-${i}`, currentPhaseTitle));
          tableLines = [];
          inTable = false;
        }
        nonTableContent.push(line);
      }
    }

    // Handle remaining content
    if (inTable && tableLines.length > 0) {
      elements.push(renderTable(tableLines, `table-final`, currentPhaseTitle));
    }
    flushNonTableContent('text-final');

    return <>{elements}</>;
  };

  const markdownComponents = {
    h1: ({ children }: any) => (
      <h1 className="text-4xl font-bold text-slate-900 mb-6 mt-12 border-b border-slate-200 pb-3">
        {children}
      </h1>
    ),
    h2: ({ children }: any) => (
      <h2 className="text-2xl font-semibold text-slate-800 mt-10 mb-4 border-l-4 border-blue-600 pl-4">
        {children}
      </h2>
    ),
    h3: ({ children }: any) => (
      <h3 className="text-xl font-medium text-slate-700 mt-6 mb-2">{children}</h3>
    ),
    p: ({ children }: any) => (
      <p className="text-slate-700 leading-relaxed mb-4">{children}</p>
    ),
    ul: ({ children }: any) => (
      <ul className="list-disc ml-6 space-y-2 text-slate-700 mb-4">{children}</ul>
    ),
    ol: ({ children }: any) => (
      <ol className="list-decimal ml-6 space-y-2 text-slate-700 mb-4">{children}</ol>
    ),
    li: ({ children }: any) => (
      <li className="leading-relaxed text-slate-700">{children}</li>
    ),
    strong: ({ children }: any) => (
      <strong className="text-slate-900 font-semibold">{children}</strong>
    ),
    blockquote: ({ children }: any) => (
      <blockquote className="border-l-4 border-blue-400 bg-blue-50 p-4 italic rounded-md my-6 text-slate-700">
        {children}
      </blockquote>
    ),
    code: ({ children, inline }: any) =>
      inline ? (
        <code className="bg-gray-100 text-blue-600 px-2 py-1 rounded text-sm font-mono">
          {children}
        </code>
      ) : (
        <pre className="bg-slate-900 text-green-400 p-4 rounded-lg overflow-x-auto text-sm font-mono">
          {children}
        </pre>
      ),
    hr: () => <hr className="my-10 border-slate-300" />,
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center">
      <div className="bg-white rounded-2xl w-[95vw] max-w-7xl h-[90vh] shadow-2xl overflow-hidden flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between bg-gradient-to-r from-slate-800 to-blue-900 px-6 py-4 text-white">
          <div className="flex items-center space-x-4">
            <div className="w-10 h-10 bg-white/10 rounded-lg flex items-center justify-center text-2xl">🗺️</div>
            <div>
              <h2 className="text-lg font-bold">Startup Roadmap</h2>
              <p className="text-blue-200 text-xs">Generated by Angel AI</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="hover:bg-white/10 p-2 rounded-full transition"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Main Content */}
        <div className="flex-1 overflow-y-auto px-8 py-6">
          {loading ? (
            <div className="h-full flex flex-col items-center justify-center text-slate-500 space-y-6">
              <div className="text-6xl">🗺️</div>
              <div className="text-center">
                <h3 className="text-xl font-semibold mb-2">Generating Your Personalized Roadmap</h3>
                <p className="text-sm mb-4">Conducting deep research and analysis...</p>
                
                {/* Progress Steps */}
                <div className="space-y-3 max-w-md">
                  <div className="flex items-center space-x-3">
                    <div className="w-6 h-6 bg-blue-500 rounded-full flex items-center justify-center text-white text-xs">✓</div>
                    <span className="text-sm">Analyzing your business information</span>
                  </div>
                  <div className="flex items-center space-x-3">
                    <div className="w-6 h-6 bg-blue-500 rounded-full flex items-center justify-center text-white text-xs">✓</div>
                    <span className="text-sm">Researching industry timelines</span>
                  </div>
                  <div className="flex items-center space-x-3">
                    <div className="w-6 h-6 bg-blue-500 rounded-full flex items-center justify-center text-white text-xs">✓</div>
                    <span className="text-sm">Analyzing regulatory requirements</span>
                  </div>
                  <div className="flex items-center space-x-3">
                    <div className="w-6 h-6 bg-blue-500 rounded-full flex items-center justify-center text-white text-xs">✓</div>
                    <span className="text-sm">Researching funding timelines</span>
                  </div>
                  <div className="flex items-center space-x-3">
                    <div className="w-6 h-6 bg-blue-500 rounded-full flex items-center justify-center text-white text-xs">✓</div>
                    <span className="text-sm">Developing market entry strategy</span>
                  </div>
                  <div className="flex items-center space-x-3">
                    <div className="w-6 h-6 bg-blue-500 rounded-full flex items-center justify-center text-white text-xs animate-pulse">⏳</div>
                    <span className="text-sm">Generating comprehensive roadmap</span>
                  </div>
                </div>
                
                <div className="mt-6 text-xs text-slate-400">
                  This may take 30-60 seconds while we conduct thorough research
                </div>
              </div>
            </div>
          ) : error ? (
            <div className="h-full flex flex-col items-center justify-center space-y-4 text-center">
              <div className="text-5xl">⚠️</div>
              <h2 className="text-lg font-bold text-slate-800">Generation Error</h2>
              <p className="text-sm text-red-600">{error}</p>
              <button
                onClick={onClose}
                className="mt-3 px-4 py-2 bg-red-600 text-white rounded-lg"
              >
                Close
              </button>
            </div>
          ) : (
            <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 text-left leading-relaxed space-y-6">
              <div className="prose prose-lg max-w-none">
                {renderMarkdownTable(plan)}
              </div>

              {/* Footer Buttons */}
              <div className="mt-12 flex flex-wrap gap-3 justify-center border-t border-slate-200 pt-6">
                <button 
                  onClick={handleDownloadPDF}
                  disabled={isDownloading}
                  className="bg-blue-600 hover:bg-blue-700 disabled:bg-blue-400 disabled:cursor-not-allowed text-white px-4 py-2 rounded-lg shadow-sm flex items-center gap-2 transition-colors duration-200"
                >
                  {isDownloading ? (
                    <>
                      <svg className="animate-spin w-4 h-4" fill="none" viewBox="0 0 24 24">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                      </svg>
                      Downloading...
                    </>
                  ) : (
                    <>
                      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                      </svg>
                      Download PDF
                    </>
                  )}
                </button>
                <button 
                  onClick={handleShareRoadmap}
                  disabled={isSharing}
                  className="bg-green-600 hover:bg-green-700 disabled:bg-green-400 disabled:cursor-not-allowed text-white px-4 py-2 rounded-lg shadow-sm flex items-center gap-2 transition-colors duration-200"
                >
                  {isSharing ? (
                    <>
                      <svg className="animate-spin w-4 h-4" fill="none" viewBox="0 0 24 24">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                      </svg>
                      Sharing...
                    </>
                  ) : (
                    <>
                      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.367 2.684 3 3 0 00-5.367-2.684z" />
                      </svg>
                      Share Roadmap
                    </>
                  )}
                </button>
                <button 
                  onClick={handleEditRoadmap}
                  className="bg-purple-600 hover:bg-purple-700 text-white px-4 py-2 rounded-lg shadow-sm flex items-center gap-2 transition-colors duration-200"
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                  </svg>
                  Edit Roadmap
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default RoadmapModal;
